# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Serendip's Workspace
email: serendip811@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This page is just small workspace
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://serendip811.github.io" # the base hostname & protocol for your site
github_username:  serendip811

# Build settings
markdown: kramdown
